// click the Inspire tab and the 100s toggle in the prototype; screenshot with the UI
import fs from 'node:fs';
import { launch, routeCdn, fileUrl } from './browser.mjs';
fs.mkdirSync('shots/ui', { recursive: true });
const b = await launch();
const p = await b.newPage({ viewport: { width: 1280, height: 800 } });
const errs = [];
p.on('pageerror', (e) => errs.push(e.message));
await routeCdn(p);
await p.goto(fileUrl('out/test.html'));
await p.waitForFunction('window.__ready === true', null, { timeout: 300000 });
await p.click('#tab-inspire');
await p.waitForFunction("window.__info().venue === 'inspire' && !window.__app.building", null, { timeout: 300000 }).catch(() => {});
await p.waitForTimeout(3000);
console.log('retract row visible', await p.isVisible('#retract-row'));
await p.screenshot({ path: 'shots/ui/inspire-out.png' });
await p.click('#seg-retract button[data-v="in"]');
await p.waitForTimeout(1500);
await p.waitForFunction('!window.__app.building', null, { timeout: 300000 }).catch(() => {});
await p.waitForTimeout(3000);
console.log('pressed', await p.getAttribute('#seg-retract button[data-v="in"]', 'aria-pressed'), 'retract', await p.evaluate('window.__app.retract'));
await p.screenshot({ path: 'shots/ui/inspire-in.png' });
console.log('errors', errs.length ? errs : 'none');
await b.close();
